# Generated by Django 4.0.6 on 2022-08-02 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Energy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('carbon_emission_factor', models.FloatField()),
                ('carbon_oxidation_rate', models.FloatField()),
                ('carbon_per_carlorific', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('performance', models.CharField(max_length=63)),
            ],
        ),
        migrations.CreateModel(
            name='OtherEnergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('default_carbon_content', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('volume', models.FloatField()),
                ('carbon_emission_factor', models.FloatField()),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='estimator.unit')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('carbon_emission_factor', models.FloatField()),
                ('equivalent_mass', models.FloatField()),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='estimator.unit')),
            ],
        ),
        migrations.CreateModel(
            name='MachinePerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('energy_volume', models.FloatField()),
                ('energy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='estimator.energy')),
                ('machine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='estimator.machine')),
            ],
        ),
        migrations.AddField(
            model_name='energy',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='estimator.unit'),
        ),
    ]
